name: local_repository
description: Local Repository Connection
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.7

dependencies:
  flutter:
    sdk: flutter
  local_api:
    path: ../local_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
